### ISSUE TITLE
DBPoolError src/main.rs:20:5

### ISSUE THREAD

**Issue by laticoda** [zupzup/warp-postgres-example#1]
Hello, i get this:

RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized] target(s) in 0.36s
     Running `target/debug/warp-postgres-example`
thread 'main' panicked at 'database can be initialized: DBPoolError(Error { kind: Connect, cause: Some(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }) })', src/main.rs:20:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: core::result::Result<T,E>::expect
  15: warp_postgres_example::main::{{closure}}
  16: <std::future::GenFuture<T> as core::future::future::Future>::poll
  17: tokio::runtime::enter::Enter::block_on::{{closure}}
  18: tokio::coop::with_budget::{{closure}}
  19: std::thread::local::LocalKey<T>::try_with
  20: std::thread::local::LocalKey<T>::with
  21: tokio::runtime::enter::Enter::block_on
  22: tokio::runtime::thread_pool::ThreadPool::block_on
  23: tokio::runtime::Runtime::block_on::{{closure}}
  24: tokio::runtime::context::enter
  25: tokio::runtime::handle::Handle::enter
  26: tokio::runtime::Runtime::block_on
  27: warp_postgres_example::main
  28: std::rt::lang_start::{{closure}}
  29: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  30: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  31: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  32: std::panicking::try
             at src/libstd/panicking.rs:281
  33: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  34: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  35: std::rt::lang_start
  36: main
  37: __libc_start_main
  38: _start

**Comment by zupzup** [comment]
Hey, this example application expects a postgres database running on port 7878 with db postgres.

You can run this with docker like this for example:

```bash
docker run -p 7878:5432 -d postgres:9.6.12
```

In order to change the default database, you can edit `db.rs` and change `postgres://postgres@127.0.0.1:7878/postgres` to the database you are running.

**Comment by laticoda** [comment]
thanks
